# config file for carafe

# port to serve on
port = 8000
# root filepath to serve from
root = "./static"

[[serve]]
# route that gets redirected
route = "/test/"
# note that this is relative to root, so the filepath for this 
# would be something like ./static/test/test.html
path = "/test/test.html"
