# config file for carafe

# port to serve on
port = 8000
# root filepath to serve from
root = "./static"

# file aliasing
[[serve]]
# route to use
route = "/test/"
# relative path to replace with.
# note that it appends to the root, like 
# ./static/test/test.html
path = "test/test.html"

# directory aliasing
[[serve]]
route = "/test2"
path = "/test"
